inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Style/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: true

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  ExtraDetails: true

Documentation:
  Enabled: false
