inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Style/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  ExtraDetails: true

Documentation:
  Enabled: false
